In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("movies_metadata.csv")

C:\Users\Sumit Mathpal\AppData\Local\Temp\ipykernel_21240\1650877637.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("movies_metadata.csv")

In [3]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
df.shape

(45466, 24)

In [5]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [6]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(13)

In [8]:
df = df.drop_duplicates().reset_index(drop=True)

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [11]:
df = df[["title","overview","tagline","genres","vote_average","popularity"]]

In [12]:
df.isnull().sum()

title               6
overview          954
tagline         25045
genres              0
vote_average        6
popularity          5
dtype: int64

In [13]:
df = df.dropna(subset=["title"])

In [14]:
df.isnull().sum()

title               0
overview          954
tagline         25039
genres              0
vote_average        0
popularity          0
dtype: int64

In [15]:
df["overview"] = df["overview"].fillna('')

In [16]:
df.isnull().sum()

title               0
overview            0
tagline         25039
genres              0
vote_average        0
popularity          0
dtype: int64

In [17]:
import ast

In [18]:
df["genres"] = df["genres"].apply(lambda x : ' '.join([i["name"] for i in ast.literal_eval(x)]))

In [19]:
df.head()

,title,overview,tagline,genres,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",NaN,Animation Comedy Family,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,Adventure Fantasy Family,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Romance Comedy,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Comedy Drama Romance,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Comedy,5.7,8.387519

In [20]:
df.isnull().sum()

title               0
overview            0
tagline         25039
genres              0
vote_average        0
popularity          0
dtype: int64

In [21]:
df["tagline"] = df["tagline"].fillna('')

In [22]:
df.isnull().sum()

title           0
overview        0
tagline         0
genres          0
vote_average    0
popularity      0
dtype: int64

In [23]:
df["tags"] = df["overview"]+" "+df["genres"]+" "+df["tagline"]

In [24]:
df

,title,overview,tagline,genres,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",,Animation Comedy Family,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,Adventure Fantasy Family,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,Romance Comedy,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,Comedy Drama Romance,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,Comedy,5.7,8.387519,Just when George Banks has recovered from his ...
...,...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,Rising and falling between a man and woman,Drama Family,4.0,0.072051,Rising and falling between a man and woman. Dr...
45449,Century of Birthing,An artist struggles to finish his work while a...,,Drama,9.0,0.178241,An artist struggles to finish his work while a...
45450,Betrayal,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,Action Drama Thriller,3.8,0.903007,"When one of her hits goes wrong, a professiona..."
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",,,0.0,0.003503,"In a small town live two brothers, one a minis..."
45452,Queerama,50 years after decriminalisation of homosexual...,,,0.0,0.163015,50 years after decriminalisation of homosexual...

In [26]:
df["tags"][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [27]:
import nltk

In [28]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [29]:
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to C:\Users\Sumit
[nltk_data]     Mathpal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Sumit
[nltk_data]     Mathpal\AppData\Roaming\nltk_data...

True

In [30]:
stopwords = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

In [33]:
def preprocess_text(text): 
    text = str(text).lower()
    text = re.sub(r'[^a-zA-z\s]','',text) #remove the panctuation
    words = text.split()
    #remove sstopwords
    words = [word for word in words if word not in stopwords]
    #lematize 
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

In [34]:
df["tags"] = df["tags"].apply(preprocess_text)

In [36]:
df["tags"][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [37]:
df = df.reset_index(drop=True)

In [55]:
indices = pd.Series(df.index,index= df["title"]).drop_duplicates()

In [56]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [57]:
#Vectorization TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
TFIDF = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words="english")

In [58]:
TFIDF_matrix = TFDF.fit_transform(df["tags"])

In [59]:
TFIDF_matrix.shape

(45447, 83351)

In [60]:
TFIDF_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1440259 stored elements and shape (45447, 83351)>

In [61]:
#cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity

In [64]:
 def recommed(title, n=10):
     if title not in indices: 
         return ["Movie Not Found"]
     idx = indices[title]
     sim_score = cosine_similarity(TFIDF_matrix[idx],TFIDF_matrix).flatten()
     similar_idx = sim_score.argsort()[::-1][1:n+1]
     return  df["title"].iloc[similar_idx]

In [70]:
print(recommed("Avenger"))

41886                        Dexter's Laboratory: Ego Trip
4367                                                D.O.A.
26695                                            Rain Fall
7842                        Now You See Him, Now You Don't
871                                 The Philadelphia Story
25089                                     Hit by Lightning
34012                                         Sharpshooter
17001    Silent Night, Deadly Night III: Better Watch Out!
7871                                          The Escapist
584                                       Tough and Deadly
Name: title, dtype: object

In [71]:
import pickle

In [72]:
pickle.dump(TFIDF_matrix,open("TFIDF_matrix.pkl","wb"))
pickle.dump(indices,open("indices.pkl","wb"))
df.to_pickle("df.pkl")
pickle.dump(TFIDF,open("TFIDF.pkl","wb"))